#!/bin/bash
# ============================================
# Mosquitto MQTT Broker Installer for Pi
# ============================================
# Usage: sudo bash install_mosquitto.sh
# Run from the gateway/ directory

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "🔧 Installing Mosquitto MQTT Broker..."
echo "======================================="

# 1. Install Mosquitto
echo ""
echo "[1/5] Installing mosquitto packages..."
sudo apt-get update -qq
sudo apt-get install -y mosquitto mosquitto-clients

# 2. Stop Mosquitto before reconfiguring
echo ""
echo "[2/5] Stopping Mosquitto for reconfiguration..."
sudo systemctl stop mosquitto 2>/dev/null || true

# 3. Load credentials from .env
MQTT_USER="admin"
MQTT_PASSWORD="password123"

if [ -f "$SCRIPT_DIR/.env" ]; then
    source_user=$(grep -oP '^MQTT_USER=\K.*' "$SCRIPT_DIR/.env" 2>/dev/null || true)
    source_pass=$(grep -oP '^MQTT_PASSWORD=\K.*' "$SCRIPT_DIR/.env" 2>/dev/null || true)
    [ -n "$source_user" ] && MQTT_USER="$source_user"
    [ -n "$source_pass" ] && MQTT_PASSWORD="$source_pass"
elif [ -f "$SCRIPT_DIR/.env.example" ]; then
    source_user=$(grep -oP '^MQTT_USER=\K.*' "$SCRIPT_DIR/.env.example" 2>/dev/null || true)
    source_pass=$(grep -oP '^MQTT_PASSWORD=\K.*' "$SCRIPT_DIR/.env.example" 2>/dev/null || true)
    [ -n "$source_user" ] && MQTT_USER="$source_user"
    [ -n "$source_pass" ] && MQTT_PASSWORD="$source_pass"
fi

# 4. Create password file
echo ""
echo "[3/5] Creating MQTT credentials (user: $MQTT_USER)..."
sudo touch /etc/mosquitto/passwd
sudo mosquitto_passwd -c -b /etc/mosquitto/passwd "$MQTT_USER" "$MQTT_PASSWORD"

# 5. Write a clean, single config (replaces the default to avoid conflicts)
echo ""
echo "[4/5] Writing Mosquitto configuration..."
sudo tee /etc/mosquitto/mosquitto.conf > /dev/null <<'MQTTCONF'
# Mosquitto Config – IoT Base Station
# Generated by install_mosquitto.sh

# Network – listen on all interfaces
listener 1883 0.0.0.0
protocol mqtt

# Authentication
allow_anonymous false
password_file /etc/mosquitto/passwd

# Persistence
persistence true
persistence_location /var/lib/mosquitto/
autosave_interval 300

# Logging
log_dest file /var/log/mosquitto/mosquitto.log
log_type error
log_type warning
log_type notice
log_timestamp true

# Limits
max_connections 50
message_size_limit 262144
max_keepalive 120
MQTTCONF
echo "  ✓ Config written to /etc/mosquitto/mosquitto.conf"

# Remove any conflicting drop-in configs
sudo rm -f /etc/mosquitto/conf.d/iot_basestation.conf 2>/dev/null || true

# 6. Create log directory
echo ""
echo "[5/5] Starting Mosquitto..."
sudo mkdir -p /var/log/mosquitto
sudo chown mosquitto:mosquitto /var/log/mosquitto

# Enable and start
sudo systemctl enable mosquitto
sudo systemctl start mosquitto
sleep 2

# Verify
if systemctl is-active --quiet mosquitto; then
    echo ""
    echo "============================================"
    echo "  ✅ Mosquitto MQTT Broker is RUNNING"
    echo "============================================"
    echo "  Port:     1883"
    echo "  User:     $MQTT_USER"
    echo "  Config:   /etc/mosquitto/mosquitto.conf"
    echo "  Logs:     /var/log/mosquitto/mosquitto.log"
    echo ""
    echo "  Test with:"
    echo "    mosquitto_sub -h localhost -t 'test/#' -u $MQTT_USER -P $MQTT_PASSWORD"
    echo "    mosquitto_pub -h localhost -t 'test/hello' -m 'Hello Pi!' -u $MQTT_USER -P $MQTT_PASSWORD"
    echo ""
else
    echo ""
    echo "  ❌ Mosquitto failed to start."
    echo "  Debug with: sudo journalctl -xeu mosquitto.service"
    echo "  Also check: sudo mosquitto -c /etc/mosquitto/mosquitto.conf -v"
fi
